+incdir+rtl/include
+incdir+third_party/hazard3/hdl
rtl/soc/soc_top.v
rtl/bus/soc_bus.v
rtl/periph/soc_uart.v
rtl/periph/soc_gpio.v
rtl/periph/soc_test_ctrl.v
rtl/bootrom/bootrom.v
third_party/picorv32/picosoc/simpleuart.v
rtl/cpu/soc_cpu_hazard3.v
rtl/cpu/soc_ahb2native.v
third_party/hazard3/hdl/hazard3_core.v
third_party/hazard3/hdl/hazard3_cpu_1port.v
third_party/hazard3/hdl/arith/hazard3_alu.v
third_party/hazard3/hdl/arith/hazard3_branchcmp.v
third_party/hazard3/hdl/arith/hazard3_mul_fast.v
third_party/hazard3/hdl/arith/hazard3_muldiv_seq.v
third_party/hazard3/hdl/arith/hazard3_onehot_encode.v
third_party/hazard3/hdl/arith/hazard3_onehot_priority.v
third_party/hazard3/hdl/arith/hazard3_onehot_priority_dynamic.v
third_party/hazard3/hdl/arith/hazard3_priority_encode.v
third_party/hazard3/hdl/arith/hazard3_shift_barrel.v
third_party/hazard3/hdl/hazard3_csr.v
third_party/hazard3/hdl/hazard3_decode.v
third_party/hazard3/hdl/hazard3_frontend.v
third_party/hazard3/hdl/hazard3_instr_decompress.v
third_party/hazard3/hdl/hazard3_irq_ctrl.v
third_party/hazard3/hdl/hazard3_pmp.v
third_party/hazard3/hdl/hazard3_power_ctrl.v
third_party/hazard3/hdl/hazard3_regfile_1w2r.v
third_party/hazard3/hdl/hazard3_triggers.v
