#!/usr/bin/env python3
"""Generate the SRAM LEF used by the flow: the PDK LEF plus ANTENNAGATEAREA on every input pin.

The PDK LEF of this macro has no antenna data, so OpenROAD's antenna checker and repair cannot
see the nets that end on SRAM inputs (project-plan.md §6.4, R6). This script copies the PDK LEF
and adds `ANTENNAGATEAREA <um^2> ;` after `DIRECTION INPUT ;` of each input pin. The area is the
transistor gate area (sum of W*L) connected to that pin inside the macro, computed from the
macro's own SPICE netlist by gate_area.py: 0.6 um^2 for 57 pins (D input of the OpenRAM DFF:
nfet W=1 + pfet W=3, L=0.15) and 0.168 um^2 for clk0/clk1. Geometry, pins and obstructions are
unchanged (the GDS is still the PDK one). docs/decisions/0008-sram-antenna-lef.md.

Usage: gen_antenna_lef.py <pdk.lef> <pdk.spice> <out.lef> [--check]
  --check   exit 1 if <out.lef> differs from what would be generated (stale copy)
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gate_area  # noqa: E402

MACRO = "sky130_sram_2kbyte_1rw1r_32x512_8"


def transform(lef, areas):
    out, done = [], set()
    pin = None
    for line in lef.splitlines(keepends=True):
        m = re.match(r"\s*PIN\s+(\S+)", line)
        if m:
            pin = m.group(1)
        elif re.match(r"\s*END\s+\S+", line) and pin and line.split()[1] == pin:
            pin = None
        out.append(line)
        if pin and re.match(r"\s*DIRECTION\s+INPUT\s*;", line):
            if pin not in areas:
                raise SystemExit(f"gen_antenna_lef: FAIL - input pin {pin} has no gate area in the SPICE netlist")
            if areas[pin] <= 0:
                raise SystemExit(f"gen_antenna_lef: FAIL - input pin {pin} has gate area {areas[pin]}")
            indent = re.match(r"(\s*)", line).group(1)
            out.append(f"{indent}ANTENNAGATEAREA {areas[pin]:.4f} ;\n")
            done.add(pin)
    missing = sorted(set(areas) - done)
    if missing:
        raise SystemExit(f"gen_antenna_lef: FAIL - input pins of the SPICE netlist not found as LEF inputs: {missing}")
    header = ("# GENERATED by ip/sram/sky130_sram_2kbyte_1rw1r_32x512_8/gen_antenna_lef.py from the PDK LEF and SPICE.\n"
              "# Adds ANTENNAGATEAREA to the input pins; nothing else differs. Do not edit by hand.\n")
    return header + "".join(out)


def main(argv):
    if len(argv) not in (4, 5) or (len(argv) == 5 and argv[4] != "--check"):
        print(__doc__)
        return 2
    lef, spice, dst = pathlib.Path(argv[1]), pathlib.Path(argv[2]), pathlib.Path(argv[3])
    sc = gate_area.parse(str(spice))
    ga = gate_area.gate_areas(sc, MACRO)
    areas = {p: ga.get(p, 0.0) for p in gate_area.inputs(str(spice), MACRO)}
    want = transform(lef.read_text(encoding="utf-8"), areas)
    if len(argv) == 5:
        have = dst.read_text(encoding="utf-8") if dst.exists() else ""
        if have != want:
            print(f"gen_antenna_lef: STALE {dst} (regenerate with: python3 {argv[0]} {lef} {spice} {dst})")
            return 1
        print(f"gen_antenna_lef: {dst} is up to date")
        return 0
    dst.write_text(want, encoding="utf-8")
    print(f"gen_antenna_lef: wrote {dst} ({len(areas)} input pins)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
