#!/usr/bin/env python3
"""Write the Hazard3 configuration header of the core-level testbench (Phase 5, ADR-0011).

usage: gen_config.py <out.vh>

The core-level tests (riscv-tests, ISS trace comparison) run the upstream Hazard3 testbench
(third_party/hazard3/test/sim/tb_common/hdl/tb.v), which takes its parameters from a
config_<name>.vh of localparams. To test the configuration the SoC really uses, this script
builds that header from the same two sources the SoC build does, instead of a hand copy:
  every `parameter NAME = value` default of third_party/hazard3/hdl/hazard3_config.vh, then
  the parameter overrides of the hazard3_cpu_1port instance in rtl/cpu/soc_cpu_hazard3.v.
Only RESET_VECTOR and MTVEC_INIT are replaced by the testbench memory map (RAM at 0x80000000,
entry at 0x80000040, the riscv-tests env_p_hazard3 layout). W_ADDR and W_DATA are left out:
tb.v declares them itself (and hazard3_config.vh says they must not change). An unresolved
macro in a value makes it FAIL.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CONFIG_VH = os.path.join(ROOT, "third_party", "hazard3", "hdl", "hazard3_config.vh")
WRAPPER = os.path.join(ROOT, "rtl", "cpu", "soc_cpu_hazard3.v")
TB_OWN = ("W_ADDR", "W_DATA")
TB_MAP = {"RESET_VECTOR": "32'h80000040", "MTVEC_INIT": "32'h80000000"}


def defaults():
    text = re.sub(r"//[^\n]*", "", open(CONFIG_VH).read())
    out = {}
    for m in re.finditer(r"\bparameter\s+(?:\[[^\]]*\]\s*)?([A-Z0-9_]+)\s*=\s*([^,;]+?)\s*(?:,|$)", text, re.M):
        out[m.group(1)] = m.group(2).strip()
    return out


def overrides():
    text = open(WRAPPER).read()
    m = re.search(r"hazard3_cpu_1port\s*#\s*\((.*?)\)\s*u_core", text, re.S)
    if not m:
        raise SystemExit("gen_config: FAIL - no hazard3_cpu_1port #(...) u_core in " + WRAPPER)
    return {k: v.strip() for k, v in re.findall(r"\.([A-Z0-9_]+)\s*\(([^()]*(?:\([^()]*\))?[^()]*)\)", m.group(1))}


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    params = defaults()
    if len(params) < 40 or "EXTENSION_A" not in params:
        print(f"gen_config: FAIL - read only {len(params)} parameters from {CONFIG_VH}")
        return 1
    ov = overrides()
    unknown = sorted(set(ov) - set(params))
    if unknown:
        print(f"gen_config: FAIL - {WRAPPER} sets unknown parameters {unknown}")
        return 1
    params.update(ov)
    params.update(TB_MAP)
    for k in TB_OWN:
        params.pop(k, None)
    bad = {k: v for k, v in params.items() if "`" in v}
    if bad:
        print(f"gen_config: FAIL - unresolved macros {bad}")
        return 1
    lines = ["// GENERATED by dv/core_hazard3/gen_config.py: the parameters of the SoC's Hazard3",
             "// (hazard3_config.vh defaults + rtl/cpu/soc_cpu_hazard3.v overrides), with the testbench",
             "// RESET_VECTOR / MTVEC_INIT. Do not edit."]
    lines += [f"localparam {k:<19} = {v};" for k, v in params.items()]
    open(argv[1], "w").write("\n".join(lines) + "\n")
    print(f"gen_config: wrote {len(params)} parameters ({len(ov)} SoC overrides) to {argv[1]}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
