#!/usr/bin/env python3
"""Generate the simulation copy of an OpenRAM SRAM behavioral model from the
untouched upstream file. Deterministic; `--check` exits 1 if the committed copy
is stale.

Transformations (each must apply exactly once, otherwise the script fails):
  1. Prepend `timescale 1ns/1ps (upstream has none).
  2. VERBOSE = 1 -> 0 (silence per-access $display).
  3. Move the `mem` array declaration before its first use. Upstream references
     mem[...] inside $display before declaring it; Icarus Verilog 13 rejects
     that ("Scope index expression is not constant"), Verilator accepts it.

Usage: gen_sim_model.py <upstream.v> <sim.v> [--check]
"""
import pathlib
import sys

HEADER = (
    "`timescale 1ns/1ps\n"
    "// GENERATED by ip/sram/gen_sim_model.py from ../upstream/ — do not edit by hand.\n"
)
VERBOSE_OLD = "  parameter VERBOSE = 1 ; //Set to 0 to only display warnings\n"
VERBOSE_NEW = "  parameter VERBOSE = 0 ; //Set to 0 to only display warnings\n"
MEM_DECL = "reg [DATA_WIDTH-1:0]    mem [0:RAM_DEPTH-1];\n"
FIRST_REG = "  reg  csb0_reg;\n"
MEM_MOVED = ("  // mem declaration moved here (Icarus needs it declared before use)\n"
             "  reg [DATA_WIDTH-1:0]    mem [0:RAM_DEPTH-1];\n\n")


def transform(src: str) -> str:
    for needle in (VERBOSE_OLD, MEM_DECL, FIRST_REG):
        if src.count(needle) != 1:
            raise SystemExit(f"gen_sim_model: expected exactly one occurrence of {needle!r}")
    out = src.replace(VERBOSE_OLD, VERBOSE_NEW)
    out = out.replace(MEM_DECL, "")
    out = out.replace(FIRST_REG, MEM_MOVED + FIRST_REG)
    return HEADER + out


def main(argv):
    if len(argv) not in (3, 4) or (len(argv) == 4 and argv[3] != "--check"):
        print(__doc__)
        return 2
    upstream, sim = pathlib.Path(argv[1]), pathlib.Path(argv[2])
    want = transform(upstream.read_text(encoding="utf-8"))
    if len(argv) == 4:
        have = sim.read_text(encoding="utf-8") if sim.exists() else ""
        if have != want:
            print(f"gen_sim_model: STALE {sim} (regenerate with: python3 {argv[0]} {upstream} {sim})")
            return 1
        print(f"gen_sim_model: {sim} is up to date")
        return 0
    sim.write_text(want, encoding="utf-8")
    print(f"gen_sim_model: wrote {sim}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
