#!/usr/bin/env bash
# =============================================================================
# rtl/scripts/synth_check.sh -- local Yosys generic synthesis of soc_top
# (make synth-check). Contract: docs/spec/soc_spec.md section 8.
#   1. Read rtl/rtl.f (+incdir+ -> -I) and the SRAM blackbox.
#   2. Run rtl/scripts/synth_check.ys: exactly one SRAM instance and
#      check -assert on the elaborated RTL; then synth -flatten, assert no
#      latch cells, exactly one sky130_sram_2kbyte_1rw1r_32x512_8 cell
#      (soc_top/sram0), check -assert on the flattened netlist.
#   3. Any "Warning:" line in the Yosys log is a FAIL (the design currently
#      synthesizes with zero warnings; a new one must be looked at). Only for
#      CPU=hazard3, two kinds from the read-only third_party/hazard3/hdl are
#      allowed, as Verilator lint waivers are (rtl/lint/waivers.vlt):
#        "Replacing memory \<name> with list of registers. See third_party/
#        hazard3/hdl/..." (small arrays such as the fetch FIFO become flops,
#        the same hardware), and the legacy "translate_off" comment warning while
#        a third_party/hazard3/hdl file is parsed (it only hides parameter
#        checks with $fatal, hazard3_mul_fast.v 34-41, hazard3_muldiv_seq.v 41-45).
#   4. Print a cell-count summary.
# Outputs: runs/rtl/synth/{read_rtl.ys,yosys.log,stat.txt}
# CPU=hazard3 (Phase 5, ADR-0011): rtl/rtl_hazard3.f with -DSOC_CPU_HAZARD3,
# outputs in runs/rtl/synth_hazard3/. Default CPU=picorv32: rtl/rtl.f.
# Exit 0 = PASS, non-zero = FAIL. Compatible with bash 3.2.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

CPU="${CPU:-picorv32}"
case "$CPU" in
    picorv32) OUT=runs/rtl/synth;          FILELIST=rtl/rtl.f;         DEFS="" ;;
    hazard3)  OUT=runs/rtl/synth_hazard3;  FILELIST=rtl/rtl_hazard3.f; DEFS=" -DSOC_CPU_HAZARD3" ;;
    *) echo "SYNTH-CHECK: FAIL (CPU must be picorv32 or hazard3, not $CPU)"; exit 1 ;;
esac
SRAM_BB=ip/sram/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.bb.v
YS=rtl/scripts/synth_check.ys
READ_YS="$OUT/read_rtl.ys"
LOG="$OUT/yosys.log"
STAT="$OUT/stat.txt"

if ! command -v yosys >/dev/null 2>&1; then
    echo "SYNTH-CHECK: FAIL (yosys not found in PATH)"
    exit 1
fi

mkdir -p "$OUT"
rm -f "$LOG" "$STAT"

# Build the read script from the filelist.
incs=""
files=""
while IFS= read -r line || [ -n "$line" ]; do
    line="$(echo "$line" | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [ -z "$line" ] && continue
    case "$line" in
        +incdir+*) incs="$incs -I${line#+incdir+}" ;;
        *)         files="$files $line" ;;
    esac
done < "$FILELIST"

{
    echo "# generated by rtl/scripts/synth_check.sh from $FILELIST (CPU=$CPU)"
    for f in $files $SRAM_BB; do
        if [ ! -f "$f" ]; then
            echo "SYNTH-CHECK: FAIL (missing source $f)" >&2
            exit 1
        fi
        echo "read_verilog$DEFS$incs $f"
    done
} > "$READ_YS"

echo "synth-check: $(yosys -V) (CPU=$CPU)"
set +e
yosys -q -l "$LOG" -p "script $READ_YS; script $YS; tee -o $STAT stat" >/dev/null 2>&1
rc=$?
set -e

if [ "$rc" -ne 0 ] || [ ! -s "$STAT" ]; then
    echo "  FAIL  yosys exited with rc=$rc; last errors from $LOG:"
    grep -nE 'ERROR|Assertion|failed' "$LOG" | tail -10 | sed 's/^/        /' || true
    echo "SYNTH-CHECK: FAIL (see $LOG)"
    exit 1
fi

# Warnings not allowed for this CPU (see the header), with their line numbers.
BAD="$OUT/warnings_not_allowed.txt"
awk -v cpu="$CPU" '
    /^Parsing Verilog input from `/ { src = $0; sub(/^Parsing Verilog input from `/, "", src); sub(/\x27.*/, "", src) }
    /^Warning:/ {
        ok = 0
        if (cpu == "hazard3") {
            if ($0 ~ /^Warning: Replacing memory \\[A-Za-z0-9_]+ with list of registers\. See third_party\/hazard3\/hdl\//) ok = 1
            if ($0 ~ /^Warning: Encountered `translate_off. comment!/ && src ~ /^third_party\/hazard3\/hdl\//) ok = 1
        }
        if (!ok) print NR ": " $0
    }' "$LOG" > "$BAD"
nallowed=$(( $(grep -c '^Warning:' "$LOG" || true) - $(wc -l < "$BAD") ))
nwarn=$(wc -l < "$BAD" | tr -d ' ')
if [ "$nwarn" -ne 0 ]; then
    echo "  FAIL  $nwarn Yosys warning(s) in $LOG:"
    head -10 "$BAD" | sed 's/^/        /'
    echo "SYNTH-CHECK: FAIL (see $LOG)"
    exit 1
fi

# Cell-count summary (from 'stat' after flatten).
echo "  PASS  RTL: exactly one SRAM instance, check -assert"
echo "  PASS  netlist: no latch cells"
echo "  PASS  netlist: exactly one sky130_sram_2kbyte_1rw1r_32x512_8 cell (soc_top/sram0)"
echo "  PASS  netlist: check -assert"
echo "  PASS  0 Yosys warnings$( [ "$nallowed" -gt 0 ] && echo " (and $nallowed allowed third_party/hazard3 warnings, see the header)")"
awk '
    $2 == "cells" && total == "" { total = $1; next }
    NF == 2 && $1 ~ /^[0-9]+$/ && $2 ~ /^[$]/ {
        if ($2 ~ /DFF/)            ff += $1
        else if ($2 == "$scopeinfo") info += $1
        else                       logic += $1
        next
    }
    NF == 2 && $1 ~ /^[0-9]+$/ && $2 == "sky130_sram_2kbyte_1rw1r_32x512_8" { sram += $1 }
    END {
        printf "  cell summary (flattened soc_top, Yosys generic cells):\n"
        printf "    total cells        %7d\n", total
        printf "    flip-flops ($*DFF*) %7d\n", ff
        printf "    logic cells         %7d\n", logic
        printf "    SRAM macros         %7d\n", sram
        printf "    $scopeinfo (no HW)  %7d\n", info
    }' "$STAT"
echo "SYNTH-CHECK: PASS (full statistics: $STAT, log: $LOG)"
