#!/usr/bin/env bash
# =============================================================================
# rtl/scripts/synth_check.sh -- local Yosys generic synthesis of soc_top
# (make synth-check). Contract: docs/spec/soc_spec.md section 8.
#   1. Read rtl/rtl.f (+incdir+ -> -I) and the SRAM blackbox.
#   2. Run rtl/scripts/synth_check.ys: exactly one SRAM instance and
#      check -assert on the elaborated RTL; then synth -flatten, assert no
#      latch cells, exactly one sky130_sram_2kbyte_1rw1r_32x512_8 cell
#      (soc_top/sram0), check -assert on the flattened netlist.
#   3. Any "Warning:" line in the Yosys log is a FAIL (the design currently
#      synthesizes with zero warnings; a new one must be looked at).
#   4. Print a cell-count summary.
# Outputs: runs/rtl/synth/{read_rtl.ys,yosys.log,stat.txt}
# Exit 0 = PASS, non-zero = FAIL. Compatible with bash 3.2.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

OUT=runs/rtl/synth
FILELIST=rtl/rtl.f
SRAM_BB=ip/sram/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.bb.v
YS=rtl/scripts/synth_check.ys
READ_YS="$OUT/read_rtl.ys"
LOG="$OUT/yosys.log"
STAT="$OUT/stat.txt"

if ! command -v yosys >/dev/null 2>&1; then
    echo "SYNTH-CHECK: FAIL (yosys not found in PATH)"
    exit 1
fi

mkdir -p "$OUT"
rm -f "$LOG" "$STAT"

# Build the read script from the filelist.
incs=""
files=""
while IFS= read -r line || [ -n "$line" ]; do
    line="$(echo "$line" | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [ -z "$line" ] && continue
    case "$line" in
        +incdir+*) incs="$incs -I${line#+incdir+}" ;;
        *)         files="$files $line" ;;
    esac
done < "$FILELIST"

{
    echo "# generated by rtl/scripts/synth_check.sh from $FILELIST"
    for f in $files $SRAM_BB; do
        if [ ! -f "$f" ]; then
            echo "SYNTH-CHECK: FAIL (missing source $f)" >&2
            exit 1
        fi
        echo "read_verilog$incs $f"
    done
} > "$READ_YS"

echo "synth-check: $(yosys -V)"
set +e
yosys -q -l "$LOG" -p "script $READ_YS; script $YS" >/dev/null 2>&1
rc=$?
set -e

if [ "$rc" -ne 0 ] || [ ! -s "$STAT" ]; then
    echo "  FAIL  yosys exited with rc=$rc; last errors from $LOG:"
    grep -nE 'ERROR|Assertion|failed' "$LOG" | tail -10 | sed 's/^/        /' || true
    echo "SYNTH-CHECK: FAIL (see $LOG)"
    exit 1
fi

nwarn=$(grep -c '^Warning:' "$LOG" || true)
if [ "$nwarn" -ne 0 ]; then
    echo "  FAIL  $nwarn Yosys warning(s) in $LOG:"
    grep -n '^Warning:' "$LOG" | head -10 | sed 's/^/        /'
    echo "SYNTH-CHECK: FAIL (see $LOG)"
    exit 1
fi

# Cell-count summary (from 'stat' after flatten).
echo "  PASS  RTL: exactly one SRAM instance, check -assert"
echo "  PASS  netlist: no latch cells"
echo "  PASS  netlist: exactly one sky130_sram_2kbyte_1rw1r_32x512_8 cell (soc_top/sram0)"
echo "  PASS  netlist: check -assert"
echo "  PASS  0 Yosys warnings"
awk '
    $2 == "cells" && total == "" { total = $1; next }
    NF == 2 && $1 ~ /^[0-9]+$/ && $2 ~ /^[$]/ {
        if ($2 ~ /DFF/)            ff += $1
        else if ($2 == "$scopeinfo") info += $1
        else                       logic += $1
        next
    }
    NF == 2 && $1 ~ /^[0-9]+$/ && $2 == "sky130_sram_2kbyte_1rw1r_32x512_8" { sram += $1 }
    END {
        printf "  cell summary (flattened soc_top, Yosys generic cells):\n"
        printf "    total cells        %7d\n", total
        printf "    flip-flops ($*DFF*) %7d\n", ff
        printf "    logic cells         %7d\n", logic
        printf "    SRAM macros         %7d\n", sram
        printf "    $scopeinfo (no HW)  %7d\n", info
    }' "$STAT"
echo "SYNTH-CHECK: PASS (full statistics: $STAT, log: $LOG)"
