// picorv32_axi replacement for `make gl-core` (Phase 2 GL ISA regression).
//
// Upstream testbench.v with -DSYNTH_TEST instantiates `picorv32_axi` without parameters.
// This module has the same ports as upstream picorv32_axi (third_party/picorv32/picorv32.v)
// and the same structure: the unmodified upstream picorv32_axi_adapter plus one `picorv32`.
// The difference is the core:
//   - GL run : `picorv32` is the hardened netlist (runs/picorv32_core/final/nl/picorv32.nl.v),
//              whose parameters are fixed by SYNTH_PARAMETERS in pnr/picorv32_core/config.json.
//   - RTL run: `picorv32` is the upstream RTL with the same parameter values, included from the
//              file generated by pnr/picorv32_core/cpu_params.py (define GL_CORE_RTL_REF).
//
// It also writes a bus transaction trace of the native memory interface, one line per completed
// transfer (mem_valid && mem_ready at a clock edge), counted in clock cycles after reset:
//   <cycle> R <addr> <rdata> <I|D>         read (I = instruction fetch)
//   <cycle> W <addr> <wdata> <wstrb>       write
// The checker (dv/gl_core/run_gl_core.py) requires the RTL and GL traces to be identical.
`timescale 1 ns / 1 ps

module picorv32_axi (
	input         clk, resetn,
	output        trap,

	// AXI4-lite master memory interface
	output        mem_axi_awvalid,
	input         mem_axi_awready,
	output [31:0] mem_axi_awaddr,
	output [ 2:0] mem_axi_awprot,

	output        mem_axi_wvalid,
	input         mem_axi_wready,
	output [31:0] mem_axi_wdata,
	output [ 3:0] mem_axi_wstrb,

	input         mem_axi_bvalid,
	output        mem_axi_bready,

	output        mem_axi_arvalid,
	input         mem_axi_arready,
	output [31:0] mem_axi_araddr,
	output [ 2:0] mem_axi_arprot,

	input         mem_axi_rvalid,
	output        mem_axi_rready,
	input  [31:0] mem_axi_rdata,

	// Pico Co-Processor Interface (PCPI), unused (ENABLE_PCPI=0)
	output        pcpi_valid,
	output [31:0] pcpi_insn,
	output [31:0] pcpi_rs1,
	output [31:0] pcpi_rs2,
	input         pcpi_wr,
	input  [31:0] pcpi_rd,
	input         pcpi_wait,
	input         pcpi_ready,

	// IRQ interface
	input  [31:0] irq,
	output [31:0] eoi,

	// Trace Interface (ENABLE_TRACE=0, constant 0)
	output        trace_valid,
	output [35:0] trace_data
);
	wire        mem_valid;
	wire [31:0] mem_addr;
	wire [31:0] mem_wdata;
	wire [ 3:0] mem_wstrb;
	wire        mem_instr;
	wire        mem_ready;
	wire [31:0] mem_rdata;

	picorv32_axi_adapter axi_adapter (
		.clk            (clk            ),
		.resetn         (resetn         ),
		.mem_axi_awvalid(mem_axi_awvalid),
		.mem_axi_awready(mem_axi_awready),
		.mem_axi_awaddr (mem_axi_awaddr ),
		.mem_axi_awprot (mem_axi_awprot ),
		.mem_axi_wvalid (mem_axi_wvalid ),
		.mem_axi_wready (mem_axi_wready ),
		.mem_axi_wdata  (mem_axi_wdata  ),
		.mem_axi_wstrb  (mem_axi_wstrb  ),
		.mem_axi_bvalid (mem_axi_bvalid ),
		.mem_axi_bready (mem_axi_bready ),
		.mem_axi_arvalid(mem_axi_arvalid),
		.mem_axi_arready(mem_axi_arready),
		.mem_axi_araddr (mem_axi_araddr ),
		.mem_axi_arprot (mem_axi_arprot ),
		.mem_axi_rvalid (mem_axi_rvalid ),
		.mem_axi_rready (mem_axi_rready ),
		.mem_axi_rdata  (mem_axi_rdata  ),
		.mem_valid      (mem_valid      ),
		.mem_instr      (mem_instr      ),
		.mem_ready      (mem_ready      ),
		.mem_addr       (mem_addr       ),
		.mem_wdata      (mem_wdata      ),
		.mem_wstrb      (mem_wstrb      ),
		.mem_rdata      (mem_rdata      )
	);

	// The PCPI inputs are tied to 0 here instead of left floating as in upstream test_synth:
	// the hardened core keeps them as ports, and floating inputs would put Z/X into the GL netlist.
	picorv32
`ifdef GL_CORE_RTL_REF
	#(
`include "cpu_params.vh"
	)
`endif
	picorv32_core (
		.clk       (clk      ),
		.resetn    (resetn   ),
		.trap      (trap     ),
		.mem_valid (mem_valid),
		.mem_addr  (mem_addr ),
		.mem_wdata (mem_wdata),
		.mem_wstrb (mem_wstrb),
		.mem_instr (mem_instr),
		.mem_ready (mem_ready),
		.mem_rdata (mem_rdata),
		.pcpi_valid(pcpi_valid),
		.pcpi_insn (pcpi_insn ),
		.pcpi_rs1  (pcpi_rs1  ),
		.pcpi_rs2  (pcpi_rs2  ),
		.pcpi_wr   (1'b0      ),
		.pcpi_rd   (32'd0     ),
		.pcpi_wait (1'b0      ),
		.pcpi_ready(1'b0      ),
		.irq       (irq       ),
		.eoi       (eoi       ),
		.trace_valid(trace_valid),
		.trace_data (trace_data )
	);

	// ---------------------------------------------------------------- bus trace
	integer trace_fd = 0;
	integer cycle = 0;
	reg [1023:0] trace_file;
	initial begin
		if ($value$plusargs("bus_trace=%s", trace_file))
			trace_fd = $fopen(trace_file, "w");
	end
	always @(posedge clk) begin
		cycle <= resetn ? cycle + 1 : 0;
		if (trace_fd != 0 && resetn && mem_valid && mem_ready) begin
			if (mem_wstrb != 4'b0000)
				$fdisplay(trace_fd, "%0d W %08x %08x %b", cycle, mem_addr, mem_wdata, mem_wstrb);
			else
				$fdisplay(trace_fd, "%0d R %08x %08x %s", cycle, mem_addr, mem_rdata, mem_instr ? "I" : "D");
		end
	end
endmodule
