#!/usr/bin/env python3
"""Generate fw/build/soc.h from rtl/include/memmap.vh (docs/spec/soc_spec.md §6.1).

Every `define SOC_* <value> in memmap.vh becomes a C/assembler macro with the same
name and numeric value. Parsing rule (from the memmap.vh header comment):
    `define NAME <width>'h<hex>   or   `define NAME <decimal>
Underscores inside numbers are separators. Defines without a value (the include
guard) are skipped; any other SOC_* define that does not match the rule is an
error, so a new constant can never be dropped silently.

The output is valid for both C and the GNU assembler (plain hex/decimal literals,
no C integer suffixes).
"""
import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_IN = REPO / "rtl" / "include" / "memmap.vh"

_DEFINE = re.compile(r"^\s*`define\s+(\w+)(?:\s+(.*?))?\s*$")
_SIZED_HEX = re.compile(r"^(\d+)'[hH]([0-9a-fA-F_]+)$")
_DECIMAL = re.compile(r"^[0-9][0-9_]*$")


def parse_memmap(path):
    """Return an ordered list of (name, value, width_or_None, literal_text)."""
    out = []
    seen = set()
    for lineno, raw in enumerate(Path(path).read_text().splitlines(), 1):
        line = raw.split("//", 1)[0]
        m = _DEFINE.match(line)
        if not m:
            continue
        name, text = m.group(1), (m.group(2) or "").strip()
        if not text:
            continue  # flag define such as the include guard
        if not name.startswith("SOC_"):
            raise ValueError(f"{path}:{lineno}: define {name} does not use the SOC_ prefix")
        if name in seen:
            raise ValueError(f"{path}:{lineno}: duplicate define {name}")
        seen.add(name)
        hm = _SIZED_HEX.match(text)
        if hm:
            width = int(hm.group(1))
            value = int(hm.group(2).replace("_", ""), 16)
            if width < 1 or value >= (1 << width):
                raise ValueError(f"{path}:{lineno}: {name} value {text} does not fit in {width} bits")
            out.append((name, value, width, text))
            continue
        if _DECIMAL.match(text):
            out.append((name, int(text.replace("_", ""), 10), None, text))
            continue
        raise ValueError(f"{path}:{lineno}: cannot parse value of {name}: {text!r}")
    if not out:
        raise ValueError(f"{path}: no SOC_* defines found")
    return out


def render(defs, src_rel):
    lines = [
        "/* Generated by fw/scripts/gen_soc_h.py from %s -- DO NOT EDIT. */" % src_rel,
        "/* Valid for C and the GNU assembler. Contract: docs/spec/soc_spec.md section 2. */",
        "#ifndef SOC_H",
        "#define SOC_H",
        "",
    ]
    width = max(len(n) for n, _, _, _ in defs)
    for name, value, bits, text in defs:
        if bits is None:
            lit = str(value)
        else:
            digits = max(1, (bits + 3) // 4)
            lit = "0x%0*X" % (digits, value)
        lines.append("#define %-*s %s  /* %s */" % (width, name, lit, text))
    lines += ["", "#endif /* SOC_H */", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--in", dest="src", default=str(DEFAULT_IN), help="memmap.vh path")
    ap.add_argument("--out", required=True, help="output soc.h path")
    args = ap.parse_args()
    src = Path(args.src)
    try:
        defs = parse_memmap(src)
    except (OSError, ValueError) as exc:
        print("gen_soc_h: ERROR: %s" % exc, file=sys.stderr)
        return 1
    try:
        src_rel = src.resolve().relative_to(REPO).as_posix()
    except ValueError:
        src_rel = src.name
    text = render(defs, src_rel)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_name(out.name + ".tmp")
    tmp.write_text(text)
    tmp.replace(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
