#!/usr/bin/env python3
"""Firmware size checker (docs/spec/soc_spec.md §6.2).

check mode : size_check.py --elf X.elf --name X --limit-sym SYM --out X.size
    Reads text/data/bss (riscv64-elf-size -A) and the linker
    symbols _free_start, _stack_limit and SYM (riscv64-elf-nm). Writes one
    summary line to --out. Exit 1 (build FAIL) when _free_start > _stack_limit
    or _free_start > SYM.
report mode: size_check.py --report size_report.txt A.size B.size ...
    Collects the per-test lines into one table.
"""
import argparse
import subprocess
import sys
from pathlib import Path

FIELDS = ["test", "text", "data", "bss", "free_start", "limit_sym", "limit", "free", "status"]


def tool_output(cmd):
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError("%s failed: %s" % (" ".join(cmd), res.stderr.strip()))
    return res.stdout


def read_symbols(nm, elf):
    syms = {}
    for line in tool_output([nm, elf]).splitlines():
        parts = line.split()
        if len(parts) == 3:
            syms[parts[2]] = int(parts[0], 16)
    return syms


def read_sizes(size, elf):
    """text = .text + .rodata, data = .data, bss = .bss (riscv64-elf-size -A)."""
    sums = {".text": 0, ".rodata": 0, ".data": 0, ".bss": 0}
    for line in tool_output([size, "-A", elf]).splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] in sums:
            sums[parts[0]] += int(parts[1])
    return sums[".text"] + sums[".rodata"], sums[".data"], sums[".bss"]


def check(args):
    syms = read_symbols(args.nm, args.elf)
    for need in ("_free_start", "_stack_limit", args.limit_sym):
        if need not in syms:
            raise RuntimeError("symbol %s missing from %s" % (need, args.elf))
    text, data, bss = read_sizes(args.size, args.elf)
    free_start = syms["_free_start"]
    limit = min(syms["_stack_limit"], syms[args.limit_sym])
    ok = free_start <= limit
    row = [args.name, str(text), str(data), str(bss), "0x%04x" % free_start,
           args.limit_sym, "0x%04x" % limit, str(limit - free_start), "PASS" if ok else "FAIL"]
    Path(args.out).write_text(" ".join(row) + "\n")
    if not ok:
        print("size_check: FAIL: %s: _free_start = 0x%04x exceeds %s = 0x%04x by %d bytes"
              % (args.name, free_start, args.limit_sym, limit, free_start - limit), file=sys.stderr)
        return 1
    print("size_check: PASS: %s: _free_start = 0x%04x <= 0x%04x (%s), %d bytes free"
          % (args.name, free_start, limit, args.limit_sym, limit - free_start))
    return 0


def report(args):
    if not args.inputs:
        raise RuntimeError("--report needs at least one .size file")
    rows = []
    for path in args.inputs:
        fields = Path(path).read_text().split()
        if len(fields) != len(FIELDS):
            raise RuntimeError("malformed size line in %s" % path)
        rows.append(fields)
    widths = [max(len(FIELDS[i]), *(len(r[i]) for r in rows)) for i in range(len(FIELDS))]
    out = [
        "# fw/build/size_report.txt - generated by fw/scripts/size_check.py",
        "# Bytes per test. free = limit - free_start. limit = min(_stack_limit, limit_sym):",
        "# _stack_limit keeps the 256-byte stack reserve free; memtest also needs the SRAM lower half.",
        "  ".join(FIELDS[i].ljust(widths[i]) for i in range(len(FIELDS))).rstrip(),
    ]
    for r in rows:
        out.append("  ".join(r[i].ljust(widths[i]) for i in range(len(FIELDS))).rstrip())
    Path(args.report).write_text("\n".join(out) + "\n")
    bad = [r[0] for r in rows if r[-1] != "PASS"]
    if bad:
        print("size_check: FAIL: over budget: %s" % ", ".join(bad), file=sys.stderr)
        return 1
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--elf")
    ap.add_argument("--name")
    ap.add_argument("--limit-sym", default="_stack_limit")
    ap.add_argument("--out")
    ap.add_argument("--nm", default="riscv64-elf-nm")
    ap.add_argument("--size", default="riscv64-elf-size")
    ap.add_argument("--report")
    ap.add_argument("inputs", nargs="*")
    args = ap.parse_args()
    try:
        if args.report:
            return report(args)
        if not (args.elf and args.name and args.out):
            ap.error("--elf, --name and --out are required in check mode")
        return check(args)
    except (OSError, RuntimeError, ValueError) as exc:
        print("size_check: ERROR: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
